name: Create Tasks
description: Create new tasks for a spec.
title: '[TASKS] '
labels:
    - create-tasks
body:
    - attributes:
        description: Which spec do you want to create tasks for?
        label: Select Spec
        options:
            - 001-hello-world
      id: spec
      type: dropdown
      validations:
        required: true
