name: Create Plan
description: Create a new plan for a spec.
title: '[PLAN] '
labels:
    - create-plan
body:
    - attributes:
        description: Which spec do you want to create a plan for?
        label: Select Spec
        options:
            - 001-hello-world
      id: spec
      type: dropdown
      validations:
        required: true
    - attributes:
        description: Provide the plan details here.
        label: Execute the implementation planning workflow using the plan template to generate design artifacts.
      id: plan
      type: textarea
      validations:
        required: true
